### ISSUE TITLE
Melhorar frase da Organização

### ISSUE THREAD

**Issue by jtemporal** [pythonsudeste/pythonsudeste2018-site#1]
Trocar:  “A Python Sudeste 2018 é organizada pela comunidade Python de São Paulo, com a ajuda da comunidade do Rio de Janeiro e Minas Gerais.”
por:  “Esse ano a Python Sudeste ~2018~ é organizada pela comunidade Python de São Paulo, com a ajuda da comunidade do Rio de Janeiro e Minas Gerais.”

**Comment by gdsrosa** [comment]
Posso fazer isso!

**Comment by biancarosa** [comment]
"esse ano" e "2018" n fica redundante?

sugiro só "Esse ano a Python Sudeste é organizada..."

**Comment by gdsrosa** [comment]
Sim, fica mesmo 😄

**Comment by jtemporal** [comment]
issoo eu esqueci de apagar o ano dps hehe vlw @biancarosa ❤

@gdsrosa manda bala!

**Comment by gdsrosa** [comment]
Pronto! Só mergear hehe

**Comment by jtemporal** [comment]
feito!

**Comment by gdsrosa** [comment]
Uhul! 🎉
