### ISSUE TITLE
Email "clicável" no site

### ISSUE THREAD

**Issue by jtemporal** [pythonsudeste/pythonsudeste2018-site#12]
seria bom colocar uma tag `href` com `mailto:` na parte da organização.
<img width="539" alt="screen shot 2017-10-19 at 8 51 57 pm" src="https://user-images.githubusercontent.com/6595551/31797886-66047fae-b50f-11e7-947f-a7d2a1082883.png">

**Comment by killerasus** [comment]
Feito no pull request #14

**Comment by mateusfmachado** [comment]
Vou fazer esse :)

**Comment by rafaelhenrique** [comment]
Resolvido no PR #14
