### ISSUE TITLE
Atualizar o package.json

### ISSUE THREAD

**Issue by jtemporal** [pythonsudeste/pythonsudeste2018-site#20]
Nosso arquivo [package.json](/pythonsudeste/pythonsudeste2018-site/blob/gh-pages/package.json) ainda contem as infos do site de 2016... seria legal ajustar para o site de 2018.

**Comment by guiconti** [comment]
Opa, eu posso fazer essa. O site de 2018 já está on? Tentei entrar e não consegui

**Comment by rafaelhenrique** [comment]
Feito em #22

**Comment by jtemporal** [comment]
>O site de 2018 já está on?

ta sim @guiconti em [pythonsudeste.org](http://pythonsudeste.org)
