### ISSUE TITLE
Apagar a master?

### ISSUE THREAD

**Issue by jtemporal** [pythonsudeste/pythonsudeste2018-site#3]
a master que ta nesse repo é uma cópia da versão do site do ano passado. continua existindo no [pythonsudeste2017-site](/pythonsudeste/pythonsudeste2017-site) podemos apagar ela e tornar a gh-pages como ramo principal do repo?

**Comment by biancarosa** [comment]
pra gente essa master ia ser o repo das atas, mas não serviu de nada hauahaua

**Comment by jtemporal** [comment]
então vou tacar fogo nela hehe

**Comment by jtemporal** [comment]
esse ano ta sendo tudo no google drive/trello
