### ISSUE TITLE
Foto da cidade na página principal

### ISSUE THREAD

**Issue by rg3915** [pythonsudeste/pythonsudeste2018-site#33]
**Sugestão:** colocar uma foto de um cartão postal da cidade de São Paulo na landpage do evento, *ex:* ponte Estaiada ou Masp.

**Comment by rafaelhenrique** [comment]
@rg3915 essa foto foi adicionada no plano de fundo do banner principal da página. Veja este PR do @jlugao :

- https://github.com/pythonsudeste/pythonsudeste2018-site/pull/24/files

Não entendi a sugestão, poderia explicar melhor?

**Comment by rg3915** [comment]
@rafaelhenrique  sim, eu vi essa foto, mas ela ficou muito escura e acho que não é um cartão postal da cidade, quem é de fora da cidade e vê, pensa "é apenas um túnel", a minha sugestão é colocar uma foto da Ponte Estaiada, visto que já sabemos o local do evento, e este é o atual cartão postal da cidade, não acha?

**Comment by rafaelhenrique** [comment]
Vamos discutir a possibilidade ....

cc @jlugao

**Comment by jtemporal** [comment]
O maior problema é achar uma imagem de alta qualidade e free para usar de cover @rg3915 se você achar um cartão postal q seja free acho que nao tem problema nenhum trocar!

**Comment by rg3915** [comment]
Achei algumas imagens free, favor escolherem uma.

https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Ponte_estaiada_Octavio_Frias_-_Sao_Paulo.jpg/1200px-Ponte_estaiada_Octavio_Frias_-_Sao_Paulo.jpg

https://www.urbanarts.com.br/imagens/produtos/023571/0/Ampliada/ponte-estaiada-sp-2.jpg

http://www.norteandovoce.com.br/wp-content/uploads/2015/07/ponte_estaiada.jpg

**Comment by rafaelhenrique** [comment]
Por que não abrir um PR? A gente te ajuda meu caro 😉

Em 20 de jan de 2018 2:08 PM, "Regis da Silva" <notifications@github.com>
escreveu:

**Comment by rg3915** [comment]
Mas precisa escolher a foto primeiro. Certo?

**Comment by rafaelhenrique** [comment]
Outra coisa, certeza que as imagens que vc mostrou são Free de fato!?

**Comment by rg3915** [comment]
Então... como conferir isso? Eu apliquei um filtro no Google Imagens? Você consegue conferir isso pelo próprio site de origem das fotos, por favor?

**Comment by rafaelhenrique** [comment]
Cara não tenho como conferir isso, vaja no site se tem algum direito autoral ou coisa do tipo. Se não for Free podemos tomar uma multa ou coisa do tipo por usar uma imagem que não é nossa.

**Comment by rg3915** [comment]
É... não consegui conferir, mas parece que já tem dono sim. Por outro lado, a foto mais barata que eu achei foi essa https://www.istockphoto.com/br/foto/ponte-estaiada-e-arranha-c%C3%A9us-em-s%C3%A3o-paulo-brasil-gm668377428-122277717 
Se não der, então deixa quieto e podem fechar essa Issue. Valeu.

**Comment by rafaelhenrique** [comment]
Olha essa última é bem legal, coloca no projeto com a marcação do iStock localmente, se ficar bonito a gente compra. O que acha? Eu topo pagar metade se vc topar

**Comment by rg3915** [comment]
Não vou poder testar agora, se você puder mais tarde, eu agradeço.
Mas vamos fazer o seguinte: votação. Se a maioria dos organizadores gostarem da foto a gente coloca. 
Eu ajudo a pagar sim.

**Comment by rafaelhenrique** [comment]
@rg3915 também não posso agora, gera com a imagem "teste" no projeto e a gente apresenta para o pessoal. O que é importante é que a imagem atual do site tem resolução 4272x2328, acho que seria interessante manter esse padrão.

**Comment by rafaelhenrique** [comment]
Apresenta == Abre um PR para o pessoal. Acho que é a melhor forma de apresentar, pois ai cada um builda local e vê como fica o resultado.

**Comment by jlugao** [comment]
Pessoal,

Tava dando uma olhada na issue aqui. Agora eu não me lembro de onde eu tirei a imagem que está atualmente, mas ela é uma imagem gratuita daquele tunel (é um tunel, viaduto, sei lá o que é aquilo), que tem ali na paulista quase na rebouças.
Eu tentei algumas outras imagens e essa foi a que compôs melhor com as cores do site e até local e tamanho das fontes. Fora que eu acho que passa uma impressão bem massa, de que a cidade está vazia, esperando as pessoas chegarem, sei lá. Tem um dinamismo massa pra caramba, vc entra no site e parece que vc vai chegar no evento por lá.
A gente pode mexer, só tomar cuidado para usar uma imagem com licença de uso comercial gratuita. Se encontrarem imagens de cartões postais (em boa qualidade) nessa condição ou que o autor libere para utilização me avisa ai que eu faço testes, aí me manda o link para a imagem / onde conseguir a imagem e a licença da imagem.
Eu costumo usar dois sites para fazer esse tipo de busca [Unsplash](https://unsplash.com) (todas as imagens livres para uso) e [Pixabay](https://pixabay.com/) (todas as imagens livres para uso, mas tem que tomar um pouco mais de cuidado). 
Enfim, se quiserem mudar me manda os links, eu testo, vejo se da pra fazer uma composição legal, se combina com o site, mando os prints pra galera decidir (que nem da outra vez) e aí a gente decide em cima disso. Blz?

Precisando grita aí

**Comment by jtemporal** [comment]
Vou fechar isso aqui. Se algm quiser fazer a mudança pode fazer e meter PRzão. Como não é priodade vou fechar.
