### ISSUE TITLE
Equalizar cores dos links do site

### ISSUE THREAD

**Issue by rafaelhenrique** [pythonsudeste/pythonsudeste2018-site#41]
Este azul do link:

![image](https://user-images.githubusercontent.com/1902333/35838993-3fcca318-0ad5-11e8-952a-50fe5acf9649.png)

É diferente deste azul:

![image](https://user-images.githubusercontent.com/1902333/35839010-506d1a54-0ad5-11e8-8f87-63228d64bf18.png)

Acho melhor adaptar para ficar tudo com o azul da segunda imagem que é #356F9F

**Comment by jtemporal** [comment]
vdd!
