### ISSUE TITLE
Colocar um call to action mais explicito para patrocinio

### ISSUE THREAD

**Issue by jtemporal** [pythonsudeste/pythonsudeste2018-site#43]
Na reunião de ontem foi mencionado que o link para ser patrocinador eh um CTA muito apagado. Que deveriamos ter algo mais explicito/chamativo. Alguem tem sugestoes?

**Comment by rafaelhenrique** [comment]
@jlugao @samukasmk ... ajuda nóis!

**Comment by rafaelhenrique** [comment]
Logo menos estaremos fechando a sessão de patrocínios (deixando somente os logos). Vou deixar como closed essa issue.
